Task9_Suspense. Custom Hooks. Products page
PrKsushka/webpack-must-have pull request #10
Opened 2022-01-05 10:48 UTC by PrKsushka

2022-01-05 11:27 UTC, StasKhitrich requested changes

2022-01-05 11:27 UTC, StasKhitrich commented on src/App.tsx
> +            <PrivateRoute exact path={links.products} component={() => <Product />} auth={authorized} />
Свойство component не надо делать коллбэком, можно просто компонент прокинуть

2022-01-05 11:27 UTC, StasKhitrich commented on src/api/dataAboutProducts.tsx
> +export const sortDataByType=(param:string, value:string)=>axios.get(`/api/products?${param}=${value}`);
Названия методов для получения данных следует начинать с fetch/get. 
- getProducts
- getProductsByAge
- getProductsByType

Но вообще, можно сделать универсальный метод ипрокидывать туда по чём сортировать (гет параметры), например создать утилиту для преобразование объекта с ключ-значение в строку &param=value?, что обычно и делается. В аксиосе кстати это встроенно уже сделано, там есть такая тема, можно body прокинуть в axios.get и он в параметры преобразуется)
[Вот пример](https://stackoverflow.com/questions/40947650/axios-get-in-url-works-but-with-second-parameter-as-object-it-doesnt)

2022-01-05 11:27 UTC, StasKhitrich commented on src/components/UI/inputRadio/inputRadio.tsx
> +import inp from "./inputRadio.module.scss";
Плохое название для переменной с классами. Не читабельно. 
Обычно переменные с классами в реакте называются styles/classes/classesList и нет нужды в каждом компоненте по разному её называть

2022-01-05 11:27 UTC, StasKhitrich commented on src/components/cardItem/cardItem.module.scss
> +        font-family: "Roboto", sans-serif;
Миксин не используешь

2022-01-05 11:27 UTC, StasKhitrich commented on src/components/searchInput/searchInput.module.scss
> +    margin: 9px;
margin-top старайся никогда не использовать. Сделай отступ сверху с помощью padding в родителе или оберни searchInput в див и сделай паддинг там. 
Это связано с [схлопыванием марджинов](https://developer.mozilla.org/ru/docs/Web/CSS/CSS_Box_Model/Mastering_margin_collapsing) и принято делать отступы слева направо, сверху вниз, это как поток флексов

2022-01-05 11:27 UTC, StasKhitrich commented on src/hooks/preloaderHook/usePreloader.tsx
> +const usePreloader: () => [JSX.Element | null, () => void, () => void] = () => {
Тип опиши перед компонентом, а тут просто используй его. Код станет чище

2022-01-05 11:27 UTC, StasKhitrich commented on src/pages/product/product.tsx
> +  const changeSelect = (e: { target: { value: React.SetStateAction<string> } }) => {
Вынеси весь сайдбар с сортировкой и фильтрацией в отдельный компонент или несколько подкомпонентов, слишком много логики в одном месте. В них пробрасывай келлбек при изменении (например) чтобы реагировать на изменение сортировки.
Ты можешь разделить на сортировку asc/desc, хранить активное состояние тут в компоненте страицы, менять его через компоненте SortAscDesc и обновлять данные через зависимый от этого стейта useEffect. Этот же useEffect может также зависеть от всех стейтов сортировок и вызывать обновление каждый раз при изменении

2022-01-05 11:27 UTC, StasKhitrich commented on src/pages/product/product.tsx
> +          <div className={product.radioButtonWrapper}>
Можешь сделать отдельный компонент RadioGroup, прокидывать туда возможные значение и он под капотом будет выводить радио баттоны. При изменении вызывать изменение стейта там где была добавлен RadioGroup. То есть не обязательно тут всё это выводить сплошняком

2022-01-05 11:27 UTC, StasKhitrich commented on src/pages/product/product.tsx
> +        <select value={selected} onChange={changeSelect} className={product.selected}>
Это стоит сделать отдельным компонентом, стили инкапсулировать в его файле стилей, тоже самое как и ниже писал или выше, что тебе нужно просто реагировать на изменение и прокидывать данные внутрь. 
Базовые компоненты типа select, radio button, input храни в component/UI

2022-01-05 11:27 UTC, StasKhitrich commented on src/store/modules/products/products.reducer.ts
> +const productReducer = (state = initialState, action: unknown) => {
1. Можешь добавить тип action, перечислив все возможные состояния
2. Добавь базовое значение action и ты сможешь убрать отключение еслинтовых правил. Ошибка в том, что первый аргумент с базовым значением есть, а дальнейшие аргументы функции без базовых значений. Обычно базовые значения ставят последним аргументам как менее обязательным. Сделай action = { type: 'DEFAULT' } например и твой стейт просто не изменится по умолчанию

2022-01-05 11:27 UTC, StasKhitrich commented on src/types/types.ts
> +  id?: number;
Почему все поля необязательные?

2022-01-05 11:33 UTC, PrKsushka commented on src/App.tsx
> +            <PrivateRoute exact path={links.products} component={() => <Product />} auth={authorized} />
Исправила

2022-01-05 11:35 UTC, PrKsushka commented on src/components/UI/inputRadio/inputRadio.tsx
> +import inp from "./inputRadio.module.scss";
Исправила

2022-01-05 11:49 UTC, PrKsushka commented on src/api/dataAboutProducts.tsx
> +export const sortDataByType=(param:string, value:string)=>axios.get(`/api/products?${param}=${value}`);
Поняла, исправила

2022-01-05 11:50 UTC, PrKsushka commented on src/components/cardItem/cardItem.module.scss
> +        font-family: "Roboto", sans-serif;
Убрала, исправила

2022-01-05 11:52 UTC, PrKsushka commented on src/components/searchInput/searchInput.module.scss
> +    margin: 9px;
Поняла, исправила)

2022-01-05 12:33 UTC, PrKsushka commented on src/hooks/preloaderHook/usePreloader.tsx
> +const usePreloader: () => [JSX.Element | null, () => void, () => void] = () => {
Исправила

2022-01-06 09:20 UTC, PrKsushka commented on src/pages/product/product.tsx
> +          <div className={product.radioButtonWrapper}>
Исправила

2022-01-06 09:33 UTC, PrKsushka commented on src/store/modules/products/products.reducer.ts
> +const productReducer = (state = initialState, action: unknown) => {
Исправила

2022-01-06 09:33 UTC, PrKsushka commented on src/pages/product/product.tsx
> +        <select value={selected} onChange={changeSelect} className={product.selected}>
Исправила

2022-01-06 10:05 UTC, PrKsushka commented on src/types/types.ts
> +  id?: number;
Этот интерфейс я переиспользовала много раз и, на сколько я помню, какие-то компоненты начали ругаться, когда я перебирала массив с объектами, соответствующими этому интерфейсу, потому что где-то одно свойство должно было быть обязательным, а в другой оно же нет

2022-01-06 10:05 UTC, PrKsushka commented on src/pages/product/product.tsx
> +  const changeSelect = (e: { target: { value: React.SetStateAction<string> } }) => {
Вынесла несколько подкомпонентов

2022-01-06 12:22 UTC, StasKhitrich approved these changes

2022-01-06 12:22 UTC, StasKhitrich commented on src/components/UI/inputRadioGroup/inputRadioGroup.tsx
> +const inputRadio: React.FunctionComponent<InputRadioGroup> = ({ obj }) => {
Название файла должно быть одинаковым с компонентом

2022-01-06 12:22 UTC, merged

2022-01-17 08:39 UTC, PrKsushka commented on src/components/UI/inputRadioGroup/inputRadioGroup.tsx
> +const inputRadio: React.FunctionComponent<InputRadioGroup> = ({ obj }) => {
Исправила