Task11_Cart page
PrKsushka/webpack-must-have pull request #11
Opened 2022-01-11 08:33 UTC by PrKsushka

2022-01-11 09:29 UTC, StasKhitrich requested changes

2022-01-11 09:29 UTC, StasKhitrich commented on src/App.tsx
> +            <PrivateRoute path={links.cart} component={Cart} auth={authorized} />
Я тут подумал, логичнее перенести authorized из APP в PrivateRoute. Тут он больше нигде не используется и нет смысла его пробрасывать отдельным параметром. Авторизация в сторе храниться, в приватном маршруте её и вытягивай

2022-01-11 09:29 UTC, StasKhitrich commented on src/components/cardItem/cardItem.tsx
> +    dispatch(addToCartAction(el));
В какие случаях может быть undefined? И что будет, если в addToCart всё же попадёт el: undefined? Проверки нет, ты сразу диспатч вызываешь

2022-01-11 09:29 UTC, StasKhitrich commented on src/components/cardItem/cardItem.tsx
> +          <button className={card.addToCart} onClick={() => addToCart(id)}>
Можно написать просто onClick={addToCart} и не прокидывать id. У тебя метод addToCart находится в области видимости компонента. ID уже в пропсах есть.
Подход с addToCart(id) был бы необходим, если бы это писалось в цикле и нужно было бы зафиксировать ID текущего элемента итерации.

2022-01-11 09:29 UTC, StasKhitrich commented on src/components/header/header.module.scss
> +    width: 35px;
Лучше делать width: 100%, max-width: 35px. 
Не столь очевидно потому, что нет адаптивности в лабораторной, но в обычной практике подход который я описал позволит всем картинкам адаптироваться и сжиматься, но не занимать больше чем указано в max-width

2022-01-11 09:29 UTC, StasKhitrich commented on src/components/header/header.tsx
> +    res = productsInCart.map((el: TopProduct) => el.quantity).reduce((sum, curr) => Number(sum) + Number(curr));
Вот вся вот эта логика с productsInCart селектором, подсчётом количества и суммой подпадает под смысл плагина reselect, где ты можешь подготовить селекторы с доп логикой и в компоненте останется лишь productsTotalPrice или ещё что-то. Попробуй перевести на reselect и создать файл selectors для модуля сторы cart.

2022-01-11 09:29 UTC, StasKhitrich commented on src/components/header/header.tsx
> +  let res: number | undefined = 0;
Название переменной ни о чем не говорит

2022-01-11 09:29 UTC, StasKhitrich commented on src/components/starRating/starRating.module.scss
> +  font-size: 14px;
Миксин

2022-01-11 09:29 UTC, StasKhitrich commented on src/components/starRating/starRating.tsx
> +        let style = inactiveColor;
Тут можешь тернарный оператор использовать:
let style = (rating !== undefined) && (index +1 <= Math.round(rating)) ? activeColor : inactiveColor

2022-01-11 09:29 UTC, StasKhitrich commented on src/components/starRating/starRating.tsx
> +          <span key={index} style={{ color: style, fontSize: size }}>
Информационный комментарий.
В многих проектах на реакте любят использовать плагины для использования CSS/SCSS подхода прямо в JSX. То есть можно стили писать не в модулях отдельных, а прямо в JSX:
[Styled Components](https://styled-components.com/) - более попуярная
[Emotions](https://emotion.sh/docs/introduction)

2022-01-11 09:29 UTC, StasKhitrich commented on src/pages/cart/cart.module.scss
> +        background: rgba(131, 0, 193, 0.38);
Цвет не переменной

2022-01-11 09:29 UTC, StasKhitrich commented on src/pages/cart/cart.module.scss
> +        font-family: "Roboto", sans-serif;
Миксин на шрифт

2022-01-11 09:29 UTC, StasKhitrich commented on src/pages/cart/cart.tsx
> +  const [checkedForDelete, setCheckedForDelete] = useState({
State можно делать не объектами, а boolean значениями, если нужно (просто тут 1 переменная в объекте и всё)

2022-01-11 09:29 UTC, StasKhitrich commented on src/pages/cart/cart.tsx
> +  function changeDate() {
Вынеси в utils/date

2022-01-11 09:29 UTC, StasKhitrich commented on src/pages/cart/cart.tsx
> +  const decreaseCount = (id?: number) => {
Что будет, если id undefined?

2022-01-11 09:29 UTC, StasKhitrich commented on src/pages/cart/cart.tsx
> +  const deleteProductFromCart = ({ id, e }: { id?: number; e: React.ChangeEvent<HTMLInputElement> }) => {
Опиши тип перед компонентом

2022-01-11 09:29 UTC, StasKhitrich commented on src/pages/cart/cart.tsx
> +        <table>
Итак, о таблицах.
В реакте много плагинов для таблиц, как и в других фреймворках, но, можно написать свой универсальный компонент для них, прокидывать внутрь конфигурацию колонок и данные. Это весьма сложный компонент, на самом деле. Но, сейчас уже не заставляю плагины делать или что-то сильно переделывать.
Однако предлагаю вынести отсюда таблицу в отдельный компонент. Можешь хранить таблицу в модуле корзинки в компонентах, можешь сделать папку Tables и хранить там все компоненты таблиц. Это очень упростит читабельность компонента страницы или мест где таблицы используются

2022-01-11 09:29 UTC, StasKhitrich commented on src/pages/cart/cart.tsx
> +  if (cart.length !== 0) {
!cart.length тоже самое делает

2022-01-11 09:29 UTC, StasKhitrich commented on src/pages/cart/cart.tsx
> +  if (cart.length !== 0) {
И уже на твой вкус, но можно сделать { !cart.length ? <Component1 /> : <Component2 /> }

2022-01-11 09:29 UTC, StasKhitrich commented on src/store/modules/products/products.reducer.ts
> +      if (foundProduct && newCart) {
В этом условии newCart всегда будет положительным. Массив с 0 элементов тоже положительный при преобразовании к логическому значению

2022-01-11 09:29 UTC, StasKhitrich commented on src/store/modules/products/products.reducer.ts
> +        if (foundIndex >= 0) {
Попробуй перед if условиями пропускать строку, читабельность повысится

2022-01-11 09:29 UTC, StasKhitrich commented on src/store/modules/products/products.reducer.ts
> +            newCart[foundIndex] = {
Прямо изменение объекта не перезапустит систему рендера реакта (в моем понимании). Тебе нужно перетереть весь объект и изминить ссылку

2022-01-11 10:13 UTC, PrKsushka commented on src/App.tsx
> +            <PrivateRoute path={links.cart} component={Cart} auth={authorized} />
Исправила

2022-01-11 10:21 UTC, PrKsushka commented on src/components/cardItem/cardItem.tsx
> +          <button className={card.addToCart} onClick={() => addToCart(id)}>
Убрала, исправила

2022-01-11 10:26 UTC, PrKsushka commented on src/components/header/header.module.scss
> +    width: 35px;
Поняла, поменяла)

2022-01-11 10:42 UTC, PrKsushka commented on src/components/header/header.tsx
> +  let res: number | undefined = 0;
Переименовала

2022-01-11 10:50 UTC, PrKsushka commented on src/components/starRating/starRating.module.scss
> +  font-size: 14px;
Исправила

2022-01-11 10:52 UTC, PrKsushka commented on src/components/starRating/starRating.tsx
> +        let style = inactiveColor;
Исправила

2022-01-11 10:54 UTC, PrKsushka commented on src/pages/cart/cart.module.scss
> +        font-family: "Roboto", sans-serif;
Исправила

2022-01-11 10:56 UTC, PrKsushka commented on src/pages/cart/cart.tsx
> +  const [checkedForDelete, setCheckedForDelete] = useState({
да, исправила

2022-01-11 11:00 UTC, PrKsushka commented on src/pages/cart/cart.tsx
> +  function changeDate() {
Вынесла

2022-01-11 11:03 UTC, PrKsushka commented on src/pages/cart/cart.tsx
> +  const decreaseCount = (id?: number) => {
Добавила проверку

2022-01-11 11:04 UTC, PrKsushka commented on src/pages/cart/cart.tsx
> +  const deleteProductFromCart = ({ id, e }: { id?: number; e: React.ChangeEvent<HTMLInputElement> }) => {
Вынесла

2022-01-11 11:06 UTC, PrKsushka commented on src/pages/cart/cart.tsx
> +  if (cart.length !== 0) {
Поняла, исправила

2022-01-11 11:09 UTC, PrKsushka commented on src/store/modules/products/products.reducer.ts
> +        if (foundIndex >= 0) {
Ок)

2022-01-11 11:11 UTC, PrKsushka commented on src/store/modules/products/products.reducer.ts
> +      if (foundProduct && newCart) {
Поняла

2022-01-11 11:14 UTC, PrKsushka commented on src/components/cardItem/cardItem.tsx
> +    dispatch(addToCartAction(el));
Добавила проверку

2022-01-11 11:18 UTC, PrKsushka commented on src/pages/cart/cart.module.scss
> +        background: rgba(131, 0, 193, 0.38);
Исправила

2022-01-11 12:05 UTC, PrKsushka commented on src/pages/cart/cart.tsx
> +        <table>
Вынесла

2022-01-11 23:05 UTC, PrKsushka commented on src/components/header/header.tsx
> +    res = productsInCart.map((el: TopProduct) => el.quantity).reduce((sum, curr) => Number(sum) + Number(curr));
сделала

2022-01-13 08:34 UTC, StasKhitrich approved these changes

2022-01-13 08:34 UTC, StasKhitrich commented on src/components/modules/cart/tables/tbody.tsx
> +import React, { useState } from "react";
У таблицы вполне может быть человеко читаемое название. Tbody ни о чем не говорит, это тег HTML вообще. Переименую во что-то типа CartProductsListTable.tsx (на свой вкус).
UPDATE: Посмотрел ниже и другие компоненты, ты таблицу разбила на части, но не вынесла эти части в отдельную общую директорию. У тебя должна быть директория конкретной таблицы в папке tables и главный компонент который объединяет всё это. 
Например, если ты хочешь сделать таблицу, но при этом разбить её на подкомпоненты, то создаешь директория компонента modules/cart/tables/CartProductsListTable/CartProductsListTable.tsx. А подкомпоненты складируй рядом или в components.

2022-01-13 08:35 UTC, merged