Task2_Routing. Header/Footer
PrKsushka/webpack-must-have pull request #2
Opened 2021-11-24 20:29 UTC by PrKsushka

2021-11-25 12:58 UTC, StasKhitrich requested changes

2021-11-25 12:58 UTC, StasKhitrich commented on .gitignore
> +/src/components/header/header.module.less
less поменяй на scss

2021-11-25 12:58 UTC, StasKhitrich commented on src/App.tsx
> +        <Header />
Не обязательно, но советую создать компонент Layout и общие элементы всех страниц выкинуть туда. Обернуть им Routes. Если появится сайдбар или типа того, добавишь это в него. 
Нужную страницу выводить как контент layout с помощью children проперти можно
[Пример](https://dev.to/olenadrugalya/layout-component-and-why-we-use-it-in-react-d8b)

2021-11-25 12:58 UTC, StasKhitrich commented on src/components/footer/footer.module.css
> +@font-face {
Нужно создать глобальные файлы стилей которые достаточно подключить 1 раз и в них, например, описать фонты проекта и другие общие для всех компонентов вещи

2021-11-25 12:58 UTC, StasKhitrich commented on src/components/footer/footer.tsx
> +        <li>
Сделай эти элемента списка через массив с данными по каждой иконке и цикл в шаблоне. Не стоит дублировать одинаковый код

2021-11-25 12:58 UTC, StasKhitrich commented on src/components/header/header.module.css
> +@font-face {
Тоже самое, общие шрифты в глобальные стили проекта

2021-11-25 12:58 UTC, StasKhitrich commented on src/components/header/header.module.css
> +  width: 500px;
Никакой фиксированной ширины, меню само займён нужное пространство на основании дочерних элементов

2021-11-25 12:58 UTC, StasKhitrich commented on src/components/header/header.tsx
> +          <Link to="/home">Home</Link>
По карточке написано, что все ссылки/страницы приложения должны хранится в неких константах, а создавая ссылки мы ссылаемся на этот объект и берем нужную информацию

2021-11-25 12:58 UTC, StasKhitrich commented on src/styles.d.ts
> +declare module "*.less" {
Не забудь убрать как перейдешь на scss/css

2021-11-25 15:57 UTC, PrKsushka commented on .gitignore
> +/src/components/header/header.module.less
Исправлено

2021-11-25 15:57 UTC, PrKsushka commented on src/App.tsx
> +        <Header />
Исправлено

2021-11-25 15:58 UTC, PrKsushka commented on src/components/footer/footer.module.css
> +@font-face {
Исправлено

2021-11-25 15:59 UTC, PrKsushka commented on src/components/footer/footer.tsx
> +        <li>
Исправлено

2021-11-25 15:59 UTC, PrKsushka commented on src/components/header/header.module.css
> +@font-face {
Исправлено

2021-11-25 16:00 UTC, PrKsushka commented on src/components/header/header.module.css
> +  width: 500px;
Исправлено. Убрала фиксированную ширину

2021-11-25 16:00 UTC, PrKsushka commented on src/components/header/header.tsx
> +          <Link to="/home">Home</Link>
Исправлено

2021-11-25 16:00 UTC, PrKsushka commented on src/styles.d.ts
> +declare module "*.less" {
Убрала

2021-11-26 10:49 UTC, StasKhitrich approved these changes

2021-11-26 10:49 UTC, merged