Task5_Modals. SignIn/SignUp
PrKsushka/webpack-must-have pull request #5
Opened 2021-12-02 10:51 UTC by PrKsushka

2021-12-02 12:04 UTC, StasKhitrich requested changes

2021-12-02 12:04 UTC, StasKhitrich commented on src/App.tsx
> +              <Signin active={true}  userLoggedIn={changeState} setUserName={setUserName} />
Я запустил твой проект, у тебя переходы на другие страницы происходят и урл меняется по итогу.
Также, твоя модалка - не совсем модалка. 
1. Добавь в модальное окно полупрозрачный фон
2. Модалка должна перекрывать интерфейс + хедер/футер и отключать скролл основного интерфейса
3. У тебя должен быть базовый компонент модального окна в который ты передаешь контент
4. Добавь использование [React Portal](https://ru.reactjs.org/docs/portals.html)
5. Формы передаваемые внутрь модалки, по заданию, хотят видеть отдельными компонентами. Чтобы можно было сделать и отдельные страницы под авторизацию и регистрацию переиспользуя компоненты форм
6. Пункт про **_When user tries to access any page beside Home > show SignIn modal before and if login successful > redirect to target page._**  означает, что если пользователь уже на главной и пытается перейти куда-то ещё, то надо показывать модальное окно, не осуществляя переход
7. Насчет прямого перехода на другие страницы (не с главной) ничего не сказано, можешь редиректить на страницы авторизации/регистрации, а можешь редиректить на главную с параметром чтобы открывало модалку авторизации (после этого было бы здорово очищать урл от этого параметра чтобы при перезагрузке опять модалку не открывало)

2021-12-06 09:50 UTC, PrKsushka commented on src/App.tsx
> +              <Signin active={true}  userLoggedIn={changeState} setUserName={setUserName} />
Исправила: 1, 2, 3, 4, 5, 6, 7 пункты

2021-12-06 10:15 UTC, StasKhitrich requested changes

2021-12-06 10:15 UTC, StasKhitrich commented on src/authenticated.tsx
> +const PrivateRoute = function ({ component: Component, auth, ...rest }: RouterPrivate) {
Название компонента и файла компонента должны быть одинаковыми. Облегчает поиск по файлам и в принципе считается хорошей практикой. И ты уверена, что файлу следует быть прям в корне src?

2021-12-06 10:15 UTC, StasKhitrich commented on src/components/header/header.tsx
> +  const [checkSignIn, setCheckSignIn] = useState<boolean>(false);
check - подразумевает, что это название некого метода для проверки чего-то, но у тебя тут просто свойство с значением true/false, некий флаг. У тебя чуть выше есть isActive, но isActive что? Стоит более понятные названия давать, сама же запутаешься.
Методы: checkSignInStatus, getSignInStatus, updateSignIn, fetchSignIn, setSignIn, deleteSignIn
Свойства: isSignIn, signInStatus
Также подумай, нужны ли тут все флаги. Складывается ощущение, что некоторые дублируют или обратны соседным стейтам.

2021-12-06 10:15 UTC, StasKhitrich commented on src/components/input/input.module.scss
> +@mixin fonts($fF, $fS, $c) {
У тебя дублирование миксина. Ты можешь объявить его в глобальных файлах стилей, например _mixin.scss и импортировать его в нужные файлы, где ты хочешь использовать миксины

2021-12-06 10:15 UTC, StasKhitrich commented on src/components/input/input.tsx
> +    <div className={signin.wrapper}>
Вообще, по семантике, тут следует делать label обёртку и вместо текста в спане, можно прям в лейбле писать или всё ещё использовать спан внутри лейбла

2021-12-06 10:15 UTC, StasKhitrich commented on src/components/input/input.tsx
> +      {nameDirty && nameError && <div style={{ color: "red" }}>{nameError}</div>}
Не стоит так стили писать когда есть возможность написать класс. Например invalid

2021-12-06 10:15 UTC, StasKhitrich commented on src/components/modal/modal.tsx
> +  const portal = document.getElementById("portal") as HTMLElement;
Тут не стоит выносить в отдельную переменную, можешь прям в createPortal эту конструкцию засунуть. Если что-то не переиспользуется, то нет особого смысла отдельные переменные делать

2021-12-06 10:15 UTC, StasKhitrich commented on src/pages/home/home.tsx
>            <CardItem key={elem.id} src={elem.image} title={elem.title} price={String(elem.price)} />
Можно сократить количество передаваемых атрибутов. Сделай чтобы CardItem принимал объект с данными для карточки, а не отдельные элементы объекта

2021-12-06 10:15 UTC, StasKhitrich commented on src/pages/home/home.tsx
> +      {state?.show ? <Signin active={modalActive} userLoggedIn={userLoggedIn} setUserName={setUserName} /> : ""}
Название компонента некорректное. Каждое новое слово с большой буквы

2021-12-06 10:15 UTC, StasKhitrich commented on src/pages/registration/registration.tsx
> +  function handleClick(e: { preventDefault: () => void }) {
Если не ошибаюсь, то ты можешь написать Event тип или MouseEvent. В любом случае, такое объявление, прямо в аргументах, не очень хорошо. Вынеси в отдельный интерфейс, если не получится с Event.
Также, можно написать вот такую конструкцию для уточнения, что кроме функции preventDefault в объектах есть и другие свойства:
[key: string]: any,
preventDefault: () => void

2021-12-06 10:15 UTC, StasKhitrich commented on src/pages/registration/registration.tsx
> +    axios
Насчёт этих разбросанных запросов, сделай единый хаб (условно) для хранения запросов к базе данных.
Подумай насчет этого, но к примеру, у тебя может быть некая директория api, где ты расположишь по модулям запросы. Методы для получения продуктов, обновления, удаления и так для других модулей. А в компонентах вся эти логика пропадёт. Компоненты должны заниматься выводом данных, а не их обработкой.
Для обработки данных существуют более умные компоненты containers/pages, которые раскидывают данные по глупым компонентам.
Вот хорошие комментарии: [тыц](https://coderoad.ru/62931118/%D0%A2%D0%B8%D0%BF%D1%8B-%D0%BA%D0%BE%D0%BC%D0%BF%D0%BE%D0%BD%D0%B5%D0%BD%D1%82%D0%BE%D0%B2-%D0%B2-React-%D0%B2%D1%81%D0%B5%D0%B3%D0%BE)

2021-12-06 10:15 UTC, StasKhitrich commented on src/pages/registration/registration.tsx
> +          localStorage.setItem("token", JSON.stringify(res.data));
Тоже самое касается работы с localStorage. Пока ты не дошла до редакса, ты можешь создать сервис для работы с localStorage. Например, это может быть некий localStorageService, который внутри содержит всю логику по получению токена, перезаписи токена и тд.
Тебе же будет достаточно в компонентах писать localStorageService.getToken() и так далее, можно же не только с токеном логику туда выкинуть.
В общем, хорошей практикой считается вынесение всей возможной логики не относящейся непосредственно к компоненту.

2021-12-06 17:42 UTC, PrKsushka commented on src/authenticated.tsx
> +const PrivateRoute = function ({ component: Component, auth, ...rest }: RouterPrivate) {
Изменила название, переместила

2021-12-06 17:43 UTC, PrKsushka commented on src/components/header/header.tsx
> +  const [checkSignIn, setCheckSignIn] = useState<boolean>(false);
Поняла, здесь поправила

2021-12-06 17:43 UTC, PrKsushka commented on src/components/input/input.module.scss
> +@mixin fonts($fF, $fS, $c) {
Сделала

2021-12-06 17:43 UTC, PrKsushka commented on src/components/input/input.tsx
> +    <div className={signin.wrapper}>
Исправила

2021-12-06 17:43 UTC, PrKsushka commented on src/components/input/input.tsx
> +      {nameDirty && nameError && <div style={{ color: "red" }}>{nameError}</div>}
Добавила класс

2021-12-06 17:44 UTC, PrKsushka commented on src/components/modal/modal.tsx
> +  const portal = document.getElementById("portal") as HTMLElement;
Сделала

2021-12-06 17:44 UTC, PrKsushka commented on src/pages/home/home.tsx
>            <CardItem key={elem.id} src={elem.image} title={elem.title} price={String(elem.price)} />
Сделала, CardItem принимает теперь объект

2021-12-06 17:45 UTC, PrKsushka commented on src/pages/home/home.tsx
> +      {state?.show ? <Signin active={modalActive} userLoggedIn={userLoggedIn} setUserName={setUserName} /> : ""}
Поняла, поменяла

2021-12-06 17:45 UTC, PrKsushka commented on src/pages/registration/registration.tsx
> +  function handleClick(e: { preventDefault: () => void }) {
Исправила

2021-12-06 17:45 UTC, PrKsushka commented on src/pages/registration/registration.tsx
> +    axios
Поняла, вынесла

2021-12-06 17:46 UTC, PrKsushka commented on src/pages/registration/registration.tsx
> +          localStorage.setItem("token", JSON.stringify(res.data));
поняла, тоже вынесла

2021-12-07 10:32 UTC, StasKhitrich requested changes

2021-12-07 10:32 UTC, StasKhitrich commented on src/api/signInRegistrationQuery.tsx
> +    .then((res) => {
Выноси в апи сами запросы. Обработку результатов верни в компоненты.
Тут ты смешиваешь логику, у тебя есть методы для получения данных (твой signInPostData), он делает свою логику, он не может и не должен знать о состоянии компонентов где его используют, он лишь делает запрос, как на это реагировать в месте вызова - это логика компонентов. Изменение состояний компонентов - логика самих компонентов.

2021-12-07 10:32 UTC, StasKhitrich commented on src/api/signInRegistrationQuery.tsx
> +      localStorageService.setElem("token", res.data);
Немного не поняла мою идею. У тебя есть постоянная необходимость работы с токеном в localStorage, так заготовь методы в сервисе на добавление токена, обновление или удаление.
Сделай внутренние приватные методы setElem, но снаружи вызывай лишь публичные по типу setToken. Не обязательно каждый раз передавать туда ключ token.

2021-12-07 10:32 UTC, StasKhitrich commented on src/api/signInRegistrationQuery.tsx
> +      const info: object = JSON.parse(localStorageService.getElem("token"));
Тоже, не доработала. Логика по парсингу тоже может быть скрыта внутри сервиса, просто делай запрос к сервису по типу: SERVICE.getToken() и всё, не нужно будет парсить каждый раз. Чем меньше логики не относящейся к рендеру в компонентах - тем лучше.

2021-12-07 10:32 UTC, StasKhitrich commented on src/api/signInRegistrationQuery.tsx
> +      setUserName(info.name);
Вот это всё вернуть в компонент

2021-12-07 10:32 UTC, StasKhitrich commented on src/api/signInRegistrationQuery.tsx
> +  axios
Тоже самое, тут только запрос и всякие настройки запроса. Обработка результатов по месту вызова

2021-12-07 10:32 UTC, StasKhitrich commented on src/components/cardItem/cardItem.tsx
> +const CardItem: React.FunctionComponent<CardProps> = function ({ item }) {
Не обязательно, но ты можешь тут использовать деструктуризацию повторно и будет что-то типа:
({ item: { image, price, title } })

2021-12-07 14:09 UTC, PrKsushka commented on src/components/cardItem/cardItem.tsx
> +const CardItem: React.FunctionComponent<CardProps> = function ({ item }) {
Сделала

2021-12-07 14:10 UTC, PrKsushka commented on src/api/signInRegistrationQuery.tsx
> +  axios
Ок, исправила

2021-12-07 14:10 UTC, PrKsushka commented on src/api/signInRegistrationQuery.tsx
> +      setUserName(info.name);
Исправила

2021-12-07 14:12 UTC, PrKsushka commented on src/api/signInRegistrationQuery.tsx
> +      const info: object = JSON.parse(localStorageService.getElem("token"));
Сделала

2021-12-07 14:12 UTC, PrKsushka commented on src/api/signInRegistrationQuery.tsx
> +      localStorageService.setElem("token", res.data);
Поняла, исправила

2021-12-07 14:12 UTC, PrKsushka commented on src/api/signInRegistrationQuery.tsx
> +    .then((res) => {
Исправила

2021-12-07 14:32 UTC, StasKhitrich approved these changes

2021-12-07 16:18 UTC, merged