Task4_create changes in header/menu
PrKsushka/webpack-must-have pull request #6
Opened 2021-12-05 23:20 UTC by PrKsushka

2021-12-06 09:47 UTC, StasKhitrich requested changes

2021-12-06 09:47 UTC, StasKhitrich commented on src/App.tsx
> +              <Route exact path="/products" component={Product} />
Зачем удалила ссылки из констант? Там по заданию надо через константы же. 
/products - в константах храни. Параметры можно добавить тут на месте

2021-12-06 09:47 UTC, StasKhitrich commented on src/components/header/headerItem.tsx
> +  const classesList = [header.item].join(" ");
У тебя тут всего 1 класс, ему не нужен массив и объединение

2021-12-06 09:47 UTC, StasKhitrich commented on src/components/header/headerList.tsx
> +        // eslint-disable-next-line react/no-array-index-key
Можно добавить id или использовать ссылку как key

2021-12-06 09:47 UTC, StasKhitrich commented on src/types/types.tsx
> +type subObj = {
У тебя тут объекты описываются, лучше через интерфейсы такое делать, типы для более простых сущностей или перечисления возможных типов:
https://frontend-stuff.com/blog/types-vs-interfaces/

2021-12-06 14:01 UTC, PrKsushka commented on src/App.tsx
> +              <Route exact path="/products" component={Product} />
Вернула константы

2021-12-06 14:01 UTC, PrKsushka commented on src/components/header/headerItem.tsx
> +  const classesList = [header.item].join(" ");
Исправила

2021-12-06 14:02 UTC, PrKsushka commented on src/components/header/headerList.tsx
> +        // eslint-disable-next-line react/no-array-index-key
Добавила id

2021-12-06 14:02 UTC, PrKsushka commented on src/types/types.tsx
> +type subObj = {
Поняла, исправила

2021-12-07 10:16 UTC, StasKhitrich approved these changes

2021-12-07 10:16 UTC, merged