Task7_Redux
PrKsushka/webpack-must-have pull request #8
Opened 2021-12-10 22:02 UTC by PrKsushka

2021-12-13 08:25 UTC, StasKhitrich requested changes

2021-12-13 08:25 UTC, StasKhitrich commented on src/types/types.tsx
> +export interface initialStateTypes {
Комментарий касаемо всего файла.
Не рационально хранить ВСЕ типы в одном файле. У тебя может быть разная структура проекта. Например, ты можешь хранить локальные интерфейсы (не задействованные глобально) прямо в файле компонента. Например интерфейсы для описания пропсов компонента. Можешь создавать файлы types.ts рядом с компонентом или в модулях отдельных, например, модуль auth с своими компонентами внутри. Ты можешь создать отдельный файл types.ts на уровне модуля с глобальными для всего модуля типами + отдельные локальные для каждого компонента (по необходимости). 
Можно переделать текущую структуру и хранить в папке types подпапку components и в ней типы для каждого компонента. Можно разбить текущий файл на несколько подфайлов по смысловой нагрузке (helpers, props, data). 
Подумай как в твоём случае будет лучше и переделай, потому что один огромный файл - плохо всегда. Старайся дробить функционал

2021-12-13 08:25 UTC, StasKhitrich commented on src/redux/store.tsx
> +export const reducer = combineReducers({
Добавь [ReduxPersist](https://www.npmjs.com/package/redux-persist). Плагин для автоматической проброски стора через localStorage (либо другие хранилища на стороне пользователя) между перезагрузками страниц. То есть у тебя пропадёт необходимость работать с localStorage самостоятельно, тебе будет достаточно хранить все данные приложения в store.
После добавления - почисти код от использования localStorage

2021-12-13 08:25 UTC, StasKhitrich commented on src/redux/reduxConstants/signInRegistrationConstants.tsx
> +export const SIGN_IN_CONFIRMED_ACTION = "SIGN_IN_CONFIRMED_ACTION";
У тебя хороший код, но есть общие практики и именования, [например](https://habr.com/ru/post/326484/).
Кратко:
- Вся информация по стору хранится в store директории (не redux)
- У тебя есть главный файл index.ts для объединения модулей и экспорта наружу того, что будет подключаться к приложению (главный reducer после combineReducers)
- У тебя могут быть подмодули (отдельные стейты типа auth с своими полями, типами, подредюсером)
- Хранение actions в файле actions.ts отдельного модуля (также как у тебя, но название файла другое и место)
- Хренение reducer в файле reducer.ts отдельного модуля
- Если есть селекторы (плагин reselect), то отдельный файл selectors/selects.ts
Прочти статью, станет понятнее

2021-12-13 08:25 UTC, StasKhitrich commented on src/redux/reducers/authReducer.tsx
> +        userData: {},
Тут можно сделать ...initialState и не расписывать каждое свойство

2021-12-13 08:25 UTC, StasKhitrich commented on src/redux/actions/authActions.tsx
> +        if (res.data) {
А если данных нет? Приложение останется в неопределенном состоянии. Стоит обработать ситуации без данных. Либо сообщение об ошибке (Alert например), либо редирект какой-то с сообщением. Либо данные по умолчанию (где это возможно).
Например, если данные пустые (а так быть не должно), то ты можешь выбрасывать исключение (throw Error) в then и код перейдет в catch (там у тебя уже есть логика)

2021-12-13 08:25 UTC, StasKhitrich commented on src/redux/actions/authActions.tsx
> +
Лишняя строка

2021-12-13 08:25 UTC, StasKhitrich commented on src/pages/signIn/signIn.tsx
> +    dispatch(signAction(formData));
Название action не подходящее. signInAction, кажется

2021-12-13 08:25 UTC, StasKhitrich commented on src/pages/signIn/signIn.tsx
>    function handleClick(e: { preventDefault: () => void }) {
Посмотри первый комментарий: [ТыЦ](https://stackoverflow.com/questions/45089866/specifying-onclick-event-type-with-typescript-and-react-konva)
Есть типы от реакта для описания таких участков как тут

2021-12-13 08:25 UTC, StasKhitrich commented on src/pages/signIn/signIn.tsx
>    const [input, setInput] = useState({
Плагины для валидации форм не использовала которые я кидал вам? Самое время освоить и отрефакторить. Там уже есть валидация и формирование объекта с данными

2021-12-13 08:25 UTC, StasKhitrich commented on src/components/header/header.tsx
> +        {userRegister ? <Registration /> : ""}
Вместо пустых строк в таких местах используется null

2021-12-13 08:25 UTC, StasKhitrich commented on src/pages/signIn/signIn.tsx
> +  const active = useSelector<RootState, boolean>((state) => state.auth.modalActive);
Есть очень простая и популярная библиотека в реакте - Reselect. Она повсеместно на всех проектах используется и это 100-процентный вопрос на каждом собесе (работал или нет). Библиотка крайне простая, но советую попробовать и понять в чём смысл. Это не обязательно, но рекомендую потратить немного времени сейчас и перейти на неё.
[Библиотека](https://github.com/reduxjs/reselect)
[Примеры](https://ru.hexlet.io/courses/js-redux/lessons/reselect/theory_unit)

2021-12-19 23:36 UTC, PrKsushka commented on src/redux/store.tsx
> +export const reducer = combineReducers({
Исправила

2021-12-19 23:36 UTC, PrKsushka commented on src/redux/reducers/authReducer.tsx
> +        userData: {},
Исправила

2021-12-19 23:36 UTC, PrKsushka commented on src/redux/actions/authActions.tsx
> +        if (res.data) {
Исправила

2021-12-19 23:36 UTC, PrKsushka commented on src/redux/actions/authActions.tsx
> +
Убрала

2021-12-19 23:36 UTC, PrKsushka commented on src/pages/signIn/signIn.tsx
> +    dispatch(signAction(formData));
Исправила

2021-12-19 23:37 UTC, PrKsushka commented on src/components/header/header.tsx
> +        {userRegister ? <Registration /> : ""}
Исправила

2021-12-19 23:39 UTC, PrKsushka commented on src/pages/signIn/signIn.tsx
>    function handleClick(e: { preventDefault: () => void }) {
Исправила

2021-12-21 10:45 UTC, PrKsushka commented on src/types/types.tsx
> +export interface initialStateTypes {
Исправила

2021-12-21 12:49 UTC, PrKsushka commented on src/pages/signIn/signIn.tsx
>    const [input, setInput] = useState({
Добавила react hook form

2021-12-21 20:23 UTC, StasKhitrich requested changes

2021-12-21 20:23 UTC, StasKhitrich commented on src/components/header/headerTypes.tsx
> +  path?: string | any;
Думаю тут можно что-то придумать и тут не обязательно any использовать. Путь либо есть строчный, либо его нет. Иногда их в массиве строк хранят. Числа тут точно не может быть, как и объекта, я полагаю

2021-12-21 20:23 UTC, StasKhitrich commented on src/components/input/validator.tsx
> +import React from "react";
Файл почему-то называется validator, хотя внутри обычный компонент input.
А выше лежит файл input закомментированный весь.
Верни компонент Input в файл Input.

2021-12-21 20:23 UTC, StasKhitrich commented on src/components/searchInput/searchInput.tsx
> +export interface Post {
Это не посты, а продукты, кажется

2021-12-21 20:23 UTC, StasKhitrich commented on src/components/searchInput/searchInput.tsx
> +export interface Post {
И не думаю, что этому интерфейсу тут место. Это что-то глобальное, разве нет?

2021-12-21 20:23 UTC, StasKhitrich commented on src/components/cardItem/cardItem.tsx
> +import { CardProps } from "./cardItemTypes";
Типы можно прям в файле с компонентом хранить.
Если хочешь хранить отдельно, то тоже можно, но мне не нравится название файлов. 
Ты можешь называть файлы в стиле ComponentName.module.scss. Например:
CardItem.types.ts или просто types.ts (он ведь итак в папке с компонентом).

2021-12-21 20:23 UTC, StasKhitrich commented on src/components/input/validator.tsx
> +        {...register(name, {
Следует прокидывать в Input объект с настройками для register и не писать всё тут в компоненте. Сейчас у тебя тут многое - хардкод. Ты можешь добавить дефолтные настройки которые могут перетираться настройками сверху: { ...defaultSetup, ...externalSetup }.
В дефолтном сетапе можешь добавить pattern в случае, если тип инпута - пароль. Или ещё что-то, тут уже на что фантазии хватит, но вообще, всю логику по валидации лучше засылать сверху по факту использования и необходимости и не хардкодить лишнюю логику внутри

2021-12-21 20:23 UTC, StasKhitrich commented on src/components/input/validator.tsx
> +        type={type}
А можно в принципе прокинуть все параметры для Input с помощью диструктуризации: {...rest}
В таком случае компонент снаружи выглядит как обычный инпут <Input type="" name="" register={register()}

2021-12-21 20:23 UTC, StasKhitrich commented on src/pages/registration/registration.tsx
> +          type="text"
type text можно по умолчанию установить в компоненте Input

2021-12-22 10:38 UTC, PrKsushka commented on src/components/input/validator.tsx
> +import React from "react";
Исправила

2021-12-22 11:08 UTC, PrKsushka commented on src/pages/registration/registration.tsx
> +          type="text"
добавила

2021-12-22 11:08 UTC, PrKsushka commented on src/components/input/validator.tsx
> +        {...register(name, {
поняла, исправила

2021-12-22 11:08 UTC, PrKsushka commented on src/components/cardItem/cardItem.tsx
> +import { CardProps } from "./cardItemTypes";
исправила

2021-12-22 11:33 UTC, StasKhitrich requested changes

2021-12-22 11:33 UTC, StasKhitrich commented on src/components/input/input.tsx
> +      {name === "name" ? errors.name?.message : errors.password?.message}
Не, не надо хардкодить ошибки в инпуте. Тут либо динамическая обработка должна присутствовать, либо снаружи ошибки пишут под инпутом

2021-12-22 11:33 UTC, StasKhitrich commented on src/pages/registration/registration.tsx
>  const Registration: React.FunctionComponent = function () {
У тебя модальные окна находятся в папке pages. По заданию у тебя именно модальные окна, а не отдельные страницы для регистрации и авторизации. 
Модальные окна хранятся в папке modals внутри components.
И названия не забудь поменять на SignInModal

2021-12-22 11:33 UTC, StasKhitrich commented on src/components/input/validatorSchema.tsx
> +export const schema = yup.object().shape({
Такие файлы принято называть schemas и располагать (как ты и сделала) рядом с местом где они нужны или глобально.
Назови схему более понятно, а файл переименую в schemas. В одном файле может быть много схем.

2021-12-22 13:24 UTC, PrKsushka commented on src/components/input/validatorSchema.tsx
> +export const schema = yup.object().shape({
Сделала

2021-12-22 13:24 UTC, PrKsushka commented on src/pages/registration/registration.tsx
>  const Registration: React.FunctionComponent = function () {
Исправила

2021-12-22 13:24 UTC, PrKsushka commented on src/components/input/input.tsx
> +      {name === "name" ? errors.name?.message : errors.password?.message}
Сделала

2021-12-22 13:24 UTC, PrKsushka commented on src/components/header/headerTypes.tsx
> +  path?: string | any;
Исправила

2021-12-22 13:39 UTC, PrKsushka commented on src/components/searchInput/searchInput.tsx
> +export interface Post {
Да, исправила

2021-12-22 13:40 UTC, PrKsushka commented on src/components/searchInput/searchInput.tsx
> +export interface Post {
Вынесла, теперь глобально

2021-12-27 11:07 UTC, merged