Task8_Profile page
PrKsushka/webpack-must-have pull request #9
Opened 2021-12-29 23:17 UTC by PrKsushka

2021-12-30 09:47 UTC, StasKhitrich requested changes

2021-12-30 09:47 UTC, StasKhitrich commented on src/api/signInRegistrationQuery.tsx
> +export const products = ({ data }: any) => axios.get("/api/getProducts", data);
Думаю, что это не подходящий файл для запроса о продуктах и его стоит вынести в отдельный файл.
+ у тебя странное название для запроса, просто products (константа не правильно названа)

2021-12-30 09:47 UTC, StasKhitrich commented on src/components/header/components/headerItem.tsx
> +    <li className={header.item} onClick={authUser}>
Смотри, по логике всё хорошо, но по наименованиям стоит поработать. Если коротко, то onAuthUser метод назвать лучше, ведь это обработка по нажатию на что-то, что должно авторизовать юзера. 
Посмотри комментарий с примером [туточки](https://stackoverflow.com/questions/60048249/what-is-the-right-name-of-event-handler-onclick-or-handleclick)

2021-12-30 09:47 UTC, StasKhitrich commented on src/components/header/components/headerItem.tsx
> +const HeaderItem: React.FunctionComponent<HeaderItemTypes> = function ({ item }) {
Можешь не тратить время на это, но, вероятнее всего, корректное название для этого компонента HeaderNavItem, а для менюшки не HeaderList, а HeaderNav. У тебя в Header есть и другие ul > li элементы, но они не выводятся с помощью этих компонентов, ты их выводишь в ручную. Значит этот HeaderItem и HeaderList более специфичны чем те и стоит это выразить через название в будущем

2021-12-30 09:47 UTC, StasKhitrich commented on src/components/modal/changePasswordModal/changePasswordModal.tsx
> +        <span className={signin.changePassword}>Change Password</span>
Можешь не исправлять, но думаю тут не спан нужен. Этот спан тут выглядит как заголовок таблицы вообще и более корректно было бы h тег использовать, типа h3

2021-12-30 09:47 UTC, StasKhitrich commented on src/components/modal/modal.tsx
> +  const body = document.getElementsByTagName("body")[0];
document.body проще и быстрее

2021-12-30 09:47 UTC, StasKhitrich commented on src/components/modal/modal.tsx
> +    body.style.overflow="visible"
auto используй.
visible буквально активирует scroll бары даже если они не нужны

2021-12-30 09:47 UTC, StasKhitrich commented on src/components/modal/modal.tsx
> +  (isActive)? body.style.overflow="hidden":body.style.overflow="visible";
Интересная конструкция, но всё же стоит useEffect использовать с зависимостью от isActive. Я думаю так правильнее было бы с позиции реакта

2021-12-30 09:47 UTC, StasKhitrich commented on src/index.html
> +    <link rel="stylesheet" href="./styles/main.scss" />
Нет, так нельзя. Ты в html файл подключаешь scss файл, что является не обработанным препроцессором форматом. 
Чтобы подключить глобально стили, ты можешь в main.tsx написать import './styles/main.scss'

2021-12-30 09:47 UTC, StasKhitrich commented on src/pages/profile/infoAboutUser/infoAboutUser.tsx
> +const InfoAboutUser: React.FunctionComponent = function () {
Насчёт специализированных для страниц компонентов. Я бы предложил создать в components подпапку modules и там, дублируя названия страниц создать подпапки. 
Например, у тебя есть компонент страницы profile.tsx. Ты не хочешь прям тут всё писать по какой-то причине. В папке components/modules/profile создаешь компоненты для этой страницы. 
Также с другими можно поступить. То есть не стоит хранить куски страницы в папке pages, пусть тут будут лишь сами компоненты страниц

2021-12-30 09:47 UTC, StasKhitrich commented on src/pages/profile/profile.module.scss
> +      height: 403px;
Никаких фикс высот. Можешь сделать width: 100%, max-width: 260px (для того чтобы картинка сама растягиваться могла от и до 260px), а высота пусть автоматическая будет. Пропорции автоматически соблюдаться будут

2021-12-30 09:47 UTC, StasKhitrich commented on src/store/store.tsx
> +declare global {
Вынеси в [d.ts](https://coderoad.ru/50463990/%D0%94%D0%BB%D1%8F-%D1%87%D0%B5%D0%B3%D0%BE-%D0%BD%D1%83%D0%B6%D0%BD%D1%8B-%D1%84%D0%B0%D0%B9%D0%BB%D1%8B-d-ts) файл

2021-12-30 10:18 UTC, PrKsushka commented on src/api/signInRegistrationQuery.tsx
> +export const products = ({ data }: any) => axios.get("/api/getProducts", data);
Исправила

2021-12-30 10:19 UTC, PrKsushka commented on src/components/header/components/headerItem.tsx
> +    <li className={header.item} onClick={authUser}>
Поняла, исправила

2021-12-30 10:22 UTC, PrKsushka commented on src/components/header/components/headerItem.tsx
> +const HeaderItem: React.FunctionComponent<HeaderItemTypes> = function ({ item }) {
Поняла, исправила

2021-12-30 10:23 UTC, PrKsushka commented on src/components/modal/changePasswordModal/changePasswordModal.tsx
> +        <span className={signin.changePassword}>Change Password</span>
Исправила

2021-12-30 10:24 UTC, PrKsushka commented on src/components/modal/modal.tsx
> +  const body = document.getElementsByTagName("body")[0];
Исправила

2021-12-30 10:27 UTC, PrKsushka commented on src/components/modal/modal.tsx
> +    body.style.overflow="visible"
Исправила

2021-12-30 10:27 UTC, PrKsushka commented on src/components/modal/modal.tsx
> +  (isActive)? body.style.overflow="hidden":body.style.overflow="visible";
Поняла, исправила

2021-12-30 10:27 UTC, PrKsushka commented on src/index.html
> +    <link rel="stylesheet" href="./styles/main.scss" />
Убрала

2021-12-30 10:30 UTC, PrKsushka commented on src/pages/profile/infoAboutUser/infoAboutUser.tsx
> +const InfoAboutUser: React.FunctionComponent = function () {
Поняла, сделала

2021-12-30 10:41 UTC, PrKsushka commented on src/pages/profile/profile.module.scss
> +      height: 403px;
Исправила

2021-12-31 08:37 UTC, PrKsushka commented on src/store/store.tsx
> +declare global {
Вынесла

2021-12-31 09:16 UTC, merged